# Generated by Django 3.0.5 on 2020-05-04 06:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typebackend', '0006_typingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PractiseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField(db_column='Typing Speed', validators=[django.core.validators.MaxValueValidator(3)])),
                ('taken_at', models.DateTimeField(verbose_name='Practised On')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TypingRecord',
        ),
    ]
