# Generated by Django 3.0.5 on 2020-04-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=12)),
                ('email_id', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
    ]
