# Generated by Django 3.0.5 on 2020-04-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typebackend', '0002_auto_20200428_0934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetails',
        ),
    ]
