# Generated by Django 3.0.5 on 2020-04-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typebackend', '0004_auto_20200429_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypingRecord',
        ),
    ]
