# Generated by Django 3.0.5 on 2020-05-04 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typebackend', '0007_auto_20200504_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiselog',
            name='speed',
            field=models.IntegerField(db_column='Typing Speed', validators=[django.core.validators.MaxValueValidator(400)]),
        ),
    ]
