# Generated by Django 3.0.5 on 2020-05-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typebackend', '0008_auto_20200504_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_from', models.CharField(max_length=25, verbose_name='Taken from')),
                ('para', models.TextField(verbose_name='Paragraph')),
            ],
        ),
    ]
