# Generated by Django 3.0.5 on 2020-05-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typebackend', '0009_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiselog',
            name='para_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='typebackend.Paragraph'),
            preserve_default=False,
        ),
    ]
