# Generated by Django 3.0.5 on 2020-05-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typebackend', '0010_practiselog_para_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practiselog',
            old_name='para_id',
            new_name='para',
        ),
    ]
