# Generated by Django 3.0.5 on 2020-05-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typebackend', '0011_auto_20200507_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='para_from',
            new_name='taken_from',
        ),
    ]
