# Generated by Django 3.0.5 on 2020-06-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typebackend', '0013_auto_20200605_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practiselog',
            old_name='speed',
            new_name='wpm',
        ),
        migrations.AddField(
            model_name='practiselog',
            name='accuracy',
            field=models.FloatField(db_column='Accuracy', default=0),
        ),
        migrations.AddField(
            model_name='practiselog',
            name='correct_words',
            field=models.IntegerField(db_column='Total correct words', default=0),
        ),
        migrations.AddField(
            model_name='practiselog',
            name='total_words',
            field=models.IntegerField(db_column='Total Words', default=0),
        ),
        migrations.AddField(
            model_name='practiselog',
            name='wrong_words',
            field=models.IntegerField(db_column='Wrong Words', default=0),
        ),
    ]
