# Generated by Django 3.0.5 on 2020-06-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typebackend', '0014_auto_20200607_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiselog',
            name='accuracy',
            field=models.FloatField(db_column='Accuracy'),
        ),
        migrations.AlterField(
            model_name='practiselog',
            name='correct_words',
            field=models.IntegerField(db_column='Total correct words'),
        ),
        migrations.AlterField(
            model_name='practiselog',
            name='total_words',
            field=models.IntegerField(db_column='Total Words'),
        ),
        migrations.AlterField(
            model_name='practiselog',
            name='wrong_words',
            field=models.IntegerField(db_column='Wrong Words'),
        ),
    ]
