# Generated by Django 3.0.5 on 2020-07-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typebackend', '0015_auto_20200607_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiselog',
            name='mode',
            field=models.CharField(default='practise', max_length=9),
            preserve_default=False,
        ),
    ]
