# Generated by Django 3.0.5 on 2020-07-24 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typebackend', '0016_practiselog_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak', models.IntegerField(default=0)),
                ('inactive_days', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_streak', models.IntegerField(default=0)),
                ('arcade_count', models.IntegerField(default=0)),
                ('practise_count', models.IntegerField(default=0)),
                ('race_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
