# Generated by Django 3.0.5 on 2020-07-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typebackend', '0017_dashboarddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboarddata',
            name='arcade_count',
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='practise_count',
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='race_count',
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='arcade',
            field=models.IntegerField(db_column='Arcade count', default=0),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='practise',
            field=models.IntegerField(db_column='Practise count', default=0),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='race',
            field=models.IntegerField(db_column='Race count', default=0),
        ),
    ]
