# Generated by Django 3.0.5 on 2020-07-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typebackend', '0018_auto_20200724_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='accuracy',
            field=models.IntegerField(db_column='Accuracy Average', default=0),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='wpm',
            field=models.IntegerField(db_column='WPM Average', default=0),
        ),
    ]
