# Generated by Django 3.0.5 on 2020-08-02 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typebackend', '0019_auto_20200730_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='accuracy',
            field=models.IntegerField(db_column='accuracy_average', default=0),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='arcade',
            field=models.IntegerField(db_column='arcade_count', default=0),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='practise',
            field=models.IntegerField(db_column='practise_count', default=0),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='race',
            field=models.IntegerField(db_column='race_count', default=0),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='wpm',
            field=models.IntegerField(db_column='WPM_average', default=0),
        ),
        migrations.AlterField(
            model_name='practiselog',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
