# Generated by Django 3.0.5 on 2020-08-02 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typebackend', '0020_auto_20200802_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='accuracy',
            field=models.IntegerField(db_column='accuracy_Average', default=0),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='wpm',
            field=models.IntegerField(db_column='wpm_average', default=0),
        ),
        migrations.AlterField(
            model_name='practiselog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
